# -*- mode: ruby -*-
# vi: set ft=ruby :
IMAGE_NAME = "bento/ubuntu-22.04-arm64"

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |rs|
    rs.memory = 2048
    rs.cpus = 2
  end

  # Ne vérifie pas les mises à jour des box à chaque démarrage.
  config.vm.box_check_update = false


  # Noeud de controle où Ansible sera intallé
  config.vm.define "controller" do |controller|
    controller.vm.box = IMAGE_NAME
    controller.vm.hostname = "controller.anslab.com"
    controller.vm.network "private_network", ip: "192.168.56.20"
    controller.vm.provision "shell", path: "bootstrap.sh"
    #controller.vm.provision "file", source: "key_gen.sh", destination: "/home/vagrant/"
    controller.vm.synced_folder "./tp", "/tp", :mount_options => ["dmode=777", "fmode=664"]
  end

  # Noeud 1
  config.vm.define "node1" do |n1|
    n1.vm.box = IMAGE_NAME
    n1.vm.hostname = "node1.wizetraining.local"
    n1.vm.network "private_network", ip: "192.168.56.21"
    n1.vm.provision "shell", path: "bootstrap.sh"
  end

  # Noeud 2
  config.vm.define "node2" do |n2|
    n2.vm.box = IMAGE_NAME
    n2.vm.hostname = "node2.wizetraining.local"
    n2.vm.network "private_network", ip: "192.168.56.22"
    n2.vm.provision "shell", path: "bootstrap.sh"
  end

  # Noeud 3
  config.vm.define "node3" do |n3|
    n3.vm.box = IMAGE_NAME
    n3.vm.hostname = "node3.wizetraining.local"
    n3.vm.network "private_network", ip: "192.168.56.23"
    n3.vm.provision "shell", path: "bootstrap.sh"
  end

end